# Generated by Django 6.0.7 on 2026-08-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0003_alter_borrowing_borrow_date"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="borrowing_expected_return_date_greater_than_borrow_date",
        ),
        migrations.RemoveConstraint(
            model_name="borrowing",
            name="actual_return_date_is_null_or_greater_than_borrow_date",
        ),
    ]
