# Generated by Django 6.0.7 on 2026-08-08 08:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        (
            "borrowings",
            "0004_remove_borrowing_borrowing_expected_return_date_greater_than_borrow_date_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_return_date__gte", models.F("borrow_date"))
                ),
                name="borrowing_expected_return_date_greater_than_borrow_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="borrowing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_return_date__isnull", True),
                    ("actual_return_date__gte", models.F("borrow_date")),
                    _connector="OR",
                ),
                name="actual_return_date_is_null_or_greater_than_borrow_date",
            ),
        ),
    ]
